remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "ko-KR"
title: "Junhyunny's Devlogs"
title_separator: "-"
name: "강준현 (Junhyunny)"
description: "소프트웨어 엔지니어 / 작가"
url: "https://junhyunny.github.io"
repository: "Junhyunny/junhyunny.github.io"
words_per_minute: 200

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-193106915-2"
    measurement_id: "G-L1KD8VFVBD"

# Site Author
author:
  name: "강준현 (Junhyunny)"
  avatar: /images/profile/profile.jpg
  bio: "소프트웨어 엔지니어 / 작가"
  location: "서울/대한민국(Seoul/South Korea)"
  email: "kang3966@naver.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/junhyun-kang-32b972201/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Junhyunny"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/14859847/junhyunny"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/junhyun-kang-32b972201/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Junhyunny"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/14859847/junhyunny"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# codepen
codepen_username: Junhyunny

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  silence_deprecations:
    - import

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  logs:
    output: true
  books:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: logs
    values:
      permalink: /:categories/:path/
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: books
    values:
      permalink: /:categories/:path/
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
